jaya_url: "https://vpn.beta.hla.triumf.ca/jaya/"
initial_transmission: #write value initial cup reading in pA
beam_energy: #beam energy in keV
beam_mass: # beam mass in amu (only needed for magnetic steering)
beam_chargestate: # beam chargestate (only needed for magnetic steering)
steering_elements:
  MEBT:Q6:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 60.0
    starting_mean: 30.0
    starting_var: 6.0
    max_incremental_change: 60.0
    set_zero_crossing: false
  MEBT:Q7:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 60.0
    starting_mean: 30.0
    starting_var: 6.0
    max_incremental_change: 60.0
    set_zero_crossing: false
  MEBT:YCB7A:CUR:
    type: steerer
    lower_bound: -100.0
    upper_bound: 100.0
    starting_mean: 0.0
    starting_var: 20.0
    max_incremental_change: 200.0
    set_zero_crossing: true
  MEBT:YCB7B:CUR:
    type: steerer
    lower_bound: -100.0
    upper_bound: 100.0
    starting_mean: 0.0
    starting_var: 20.0
    max_incremental_change: 200.0
    set_zero_crossing: true
  MEBT:Q8:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 60.0
    starting_mean: 30.0
    starting_var: 6.0
    max_incremental_change: 60.0
    set_zero_crossing: false
  MEBT:Q9:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 60.0
    starting_mean: 30.0
    starting_var: 6.0
    max_incremental_change: 60.0
    set_zero_crossing: false
  MEBT:XCB9:CUR:
    type: steerer
    lower_bound: -100.0
    upper_bound: 100.0
    starting_mean: 0.0
    starting_var: 20.0
    max_incremental_change: 200.0
    set_zero_crossing: true
  MEBT:YCB9:CUR:
    type: steerer
    lower_bound: -100.0
    upper_bound: 100.0
    starting_mean: 0.0
    starting_var: 20.0
    max_incremental_change: 200.0
    set_zero_crossing: true
  MEBT:Q10:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 60.0
    starting_mean: 30.0
    starting_var: 6.0
    max_incremental_change: 60.0
    set_zero_crossing: false
  MEBT:Q11:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 60.0
    starting_mean: 30.0
    starting_var: 6.0
    max_incremental_change: 60.0
    set_zero_crossing: false
  MEBT:YCB11:CUR:
    type: steerer
    lower_bound: -3.0
    upper_bound: 3.0
    starting_mean: 0.0
    starting_var: 0.6
    max_incremental_change: 6.0
    set_zero_crossing: true
  MEBT:Q12:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 60.0
    starting_mean: 30.0
    starting_var: 6.0
    max_incremental_change: 60.0
    set_zero_crossing: false
  MEBT:XCB12:CUR:
    type: steerer
    lower_bound: -3.0
    upper_bound: 3.0
    starting_mean: 0.0
    starting_var: 0.6
    max_incremental_change: 6.0
    set_zero_crossing: true
  MEBT:Q13:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 60.0
    starting_mean: 30.0
    starting_var: 6.0
    max_incremental_change: 60.0
    set_zero_crossing: false
  DTL:Q1:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 250.0
    starting_mean: 125.0
    starting_var: 25.0
    max_incremental_change: 250.0
    set_zero_crossing: false
  DTL:Q2:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 250.0
    starting_mean: 125.0
    starting_var: 25.0
    max_incremental_change: 250.0
    set_zero_crossing: false
  DTL:XYCB2:XCUR:
    type: steerer
    lower_bound: -200.0
    upper_bound: 200.0
    starting_mean: 0.0
    starting_var: 40.0
    max_incremental_change: 400.0
    set_zero_crossing: true
  DTL:XYCB2:YCUR:
    type: steerer
    lower_bound: -200.0
    upper_bound: 200.0
    starting_mean: 0.0
    starting_var: 40.0
    max_incremental_change: 400.0
    set_zero_crossing: true
  DTL:Q3:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 250.0
    starting_mean: 125.0
    starting_var: 25.0
    max_incremental_change: 250.0
    set_zero_crossing: false
  DTL:Q4:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 250.0
    starting_mean: 125.0
    starting_var: 25.0
    max_incremental_change: 250.0
    set_zero_crossing: false
  DTL:Q5:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 250.0
    starting_mean: 125.0
    starting_var: 25.0
    max_incremental_change: 250.0
    set_zero_crossing: false
  DTL:XYCB5:XCUR:
    type: steerer
    lower_bound: -200.0
    upper_bound: 200.0
    starting_mean: 0.0
    starting_var: 40.0
    max_incremental_change: 400.0
    set_zero_crossing: true
  DTL:XYCB5:YCUR:
    type: steerer
    lower_bound: -200.0
    upper_bound: 200.0
    starting_mean: 0.0
    starting_var: 40.0
    max_incremental_change: 400.0
    set_zero_crossing: true
  DTL:Q6:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 250.0
    starting_mean: 125.0
    starting_var: 25.0
    max_incremental_change: 250.0
    set_zero_crossing: false
  DTL:Q7:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 250.0
    starting_mean: 125.0
    starting_var: 25.0
    max_incremental_change: 250.0
    set_zero_crossing: false
  DTL:Q8:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 250.0
    starting_mean: 125.0
    starting_var: 25.0
    max_incremental_change: 250.0
    set_zero_crossing: false
  DTL:XYCB8:XCUR:
    type: steerer
    lower_bound: -200.0
    upper_bound: 200.0
    starting_mean: 0.0
    starting_var: 40.0
    max_incremental_change: 400.0
    set_zero_crossing: true
  DTL:XYCB8:YCUR:
    type: steerer
    lower_bound: -200.0
    upper_bound: 200.0
    starting_mean: 0.0
    starting_var: 40.0
    max_incremental_change: 400.0
    set_zero_crossing: true
  DTL:Q9:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 250.0
    starting_mean: 125.0
    starting_var: 25.0
    max_incremental_change: 250.0
    set_zero_crossing: false
  DTL:Q10:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 250.0
    starting_mean: 125.0
    starting_var: 25.0
    max_incremental_change: 250.0
    set_zero_crossing: false
  DTL:Q11:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 250.0
    starting_mean: 125.0
    starting_var: 25.0
    max_incremental_change: 250.0
    set_zero_crossing: false
  DTL:XYCB11:XCUR:
    type: steerer
    lower_bound: -200.0
    upper_bound: 200.0
    starting_mean: 0.0
    starting_var: 40.0
    max_incremental_change: 400.0
    set_zero_crossing: true
  DTL:XYCB11:YCUR:
    type: steerer
    lower_bound: -200.0
    upper_bound: 200.0
    starting_mean: 0.0
    starting_var: 40.0
    max_incremental_change: 400.0
    set_zero_crossing: true
  DTL:Q12:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 250.0
    starting_mean: 125.0
    starting_var: 25.0
    max_incremental_change: 250.0
    set_zero_crossing: false
  HEBT:XCB0:CUR:
    type: steerer
    lower_bound: -100.0
    upper_bound: 100.0
    starting_mean: 0.0
    starting_var: 20.0
    max_incremental_change: 200.0
    set_zero_crossing: true
  HEBT:YCB0:CUR:
    type: steerer
    lower_bound: -100.0
    upper_bound: 100.0
    starting_mean: 0.0
    starting_var: 20.0
    max_incremental_change: 200.0
    set_zero_crossing: true
  HEBT:Q1:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 60.0
    starting_mean: 30.0
    starting_var: 6.0
    max_incremental_change: 60.0
    set_zero_crossing: false
  HEBT:Q2:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 60.0
    starting_mean: 30.0
    starting_var: 6.0
    max_incremental_change: 60.0
    set_zero_crossing: false
  HEBT:XCB2:CUR:
    type: steerer
    lower_bound: -100.0
    upper_bound: 100.0
    starting_mean: 0.0
    starting_var: 20.0
    max_incremental_change: 200.0
    set_zero_crossing: true
  HEBT:YCB2:CUR:
    type: steerer
    lower_bound: -100.0
    upper_bound: 100.0
    starting_mean: 0.0
    starting_var: 20.0
    max_incremental_change: 200.0
    set_zero_crossing: true
  HEBT:Q3:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 60.0
    starting_mean: 30.0
    starting_var: 6.0
    max_incremental_change: 60.0
    set_zero_crossing: false
  HEBT:Q5:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 60.0
    starting_mean: 30.0
    starting_var: 6.0
    max_incremental_change: 60.0
    set_zero_crossing: false
  HEBT:XCB5:CUR:
    type: steerer
    lower_bound: -3.0
    upper_bound: 3.0
    starting_mean: 0.0
    starting_var: 0.6
    max_incremental_change: 6.0
    set_zero_crossing: true
  HEBT:YCB5:CUR:
    type: steerer
    lower_bound: -3.0
    upper_bound: 3.0
    starting_mean: 0.0
    starting_var: 0.6
    max_incremental_change: 6.0
    set_zero_crossing: true
  HEBT:Q6:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 60.0
    starting_mean: 30.0
    starting_var: 6.0
    max_incremental_change: 60.0
    set_zero_crossing: false
  HEBT:Q7:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 60.0
    starting_mean: 30.0
    starting_var: 6.0
    max_incremental_change: 60.0
    set_zero_crossing: false
  HEBT:Q8:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 60.0
    starting_mean: 30.0
    starting_var: 6.0
    max_incremental_change: 60.0
    set_zero_crossing: false
  HEBT:XCB8:CUR:
    type: steerer
    lower_bound: -100.0
    upper_bound: 100.0
    starting_mean: 0.0
    starting_var: 20.0
    max_incremental_change: 200.0
    set_zero_crossing: true
  HEBT:YCB8:CUR:
    type: steerer
    lower_bound: -100.0
    upper_bound: 100.0
    starting_mean: 0.0
    starting_var: 20.0
    max_incremental_change: 200.0
    set_zero_crossing: true
  HEBT:Q9:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 60.0
    starting_mean: 30.0
    starting_var: 6.0
    max_incremental_change: 60.0
    set_zero_crossing: false
  HEBT:Q10:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 60.0
    starting_mean: 30.0
    starting_var: 6.0
    max_incremental_change: 60.0
    set_zero_crossing: false
  HEBT:XCB10:CUR:
    type: steerer
    lower_bound: -100.0
    upper_bound: 100.0
    starting_mean: 0.0
    starting_var: 20.0
    max_incremental_change: 200.0
    set_zero_crossing: true
  HEBT:YCB10:CUR:
    type: steerer
    lower_bound: -100.0
    upper_bound: 100.0
    starting_mean: 0.0
    starting_var: 20.0
    max_incremental_change: 200.0
    set_zero_crossing: true
  HEBT:Q11:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 60.0
    starting_mean: 30.0
    starting_var: 6.0
    max_incremental_change: 60.0
    set_zero_crossing: false
  HEBT:Q12:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 60.0
    starting_mean: 30.0
    starting_var: 6.0
    max_incremental_change: 60.0
    set_zero_crossing: false
  HEBT:XCB12:CUR:
    type: steerer
    lower_bound: -3.0
    upper_bound: 3.0
    starting_mean: 0.0
    starting_var: 0.6
    max_incremental_change: 6.0
    set_zero_crossing: true
  HEBT:YCB12:CUR:
    type: steerer
    lower_bound: -3.0
    upper_bound: 3.0
    starting_mean: 0.0
    starting_var: 0.6
    max_incremental_change: 6.0
    set_zero_crossing: true
  HEBT2:Q1:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 125.0
    starting_mean: 62.5
    starting_var: 12.5
    max_incremental_change: 125.0
    set_zero_crossing: false
  HEBT2:XCB2:CUR:
    type: steerer
    lower_bound: -3.0
    upper_bound: 3.0
    starting_mean: 0.0
    starting_var: 0.6
    max_incremental_change: 6.0
    set_zero_crossing: true
  HEBT2:YCB2:CUR:
    type: steerer
    lower_bound: -3.0
    upper_bound: 3.0
    starting_mean: 0.0
    starting_var: 0.6
    max_incremental_change: 6.0
    set_zero_crossing: true
  HEBT2:Q3:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 60.0
    starting_mean: 30.0
    starting_var: 6.0
    max_incremental_change: 60.0
    set_zero_crossing: false
  HEBT2:Q4:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 60.0
    starting_mean: 30.0
    starting_var: 6.0
    max_incremental_change: 60.0
    set_zero_crossing: false
  HEBT2:XCB4:CUR:
    type: steerer
    lower_bound: -100.0
    upper_bound: 100.0
    starting_mean: 0.0
    starting_var: 20.0
    max_incremental_change: 200.0
    set_zero_crossing: true
  HEBT2:YCB4:CUR:
    type: steerer
    lower_bound: -100.0
    upper_bound: 100.0
    starting_mean: 0.0
    starting_var: 20.0
    max_incremental_change: 200.0
    set_zero_crossing: true
  HEBT2:Q5:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 60.0
    starting_mean: 30.0
    starting_var: 6.0
    max_incremental_change: 60.0
    set_zero_crossing: false
  HEBT2:Q6:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 60.0
    starting_mean: 30.0
    starting_var: 6.0
    max_incremental_change: 60.0
    set_zero_crossing: false
  HEBT2:XCB6:CUR:
    type: steerer
    lower_bound: -100.0
    upper_bound: 100.0
    starting_mean: 0.0
    starting_var: 20.0
    max_incremental_change: 200.0
    set_zero_crossing: true
  HEBT2:YCB6:CUR:
    type: steerer
    lower_bound: -100.0
    upper_bound: 100.0
    starting_mean: 0.0
    starting_var: 20.0
    max_incremental_change: 200.0
    set_zero_crossing: true
  HEBT2:Q7:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 60.0
    starting_mean: 30.0
    starting_var: 6.0
    max_incremental_change: 60.0
    set_zero_crossing: false
  HEBT2:Q8:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 60.0
    starting_mean: 30.0
    starting_var: 6.0
    max_incremental_change: 60.0
    set_zero_crossing: false
  DRA:Q1:CUR:
    type: quad
    pv: DRA:Q1:RDCUR
    measure_points: 20
    trim_ratio: 0.2
    ptime: 0.01
    scale_factor: 1000000000000
  DRA:Q2:CUR:
    type: quad
    pv: DRA:Q2:RDCUR
    measure_points: 20
    trim_ratio: 0.2
    ptime: 0.01
    scale_factor: 1000000000000
measurement_device:
  type: fc
  loc: 3540.44648
  pv: DRA:FC1:SCALECUR
  measure_points: 20
  trim_ratio: 0.2
  ptime: 0.01
  scale_factor: 1000000000000
common_elements: {}
#scale factor is a fudge factor to make all FC measurements be in pA
