jaya_url: "https://vpn.beta.hla.triumf.ca/jaya/"
initial_transmission: #write value initial cup reading in pA
beam_energy: #beam energy in keV
beam_mass: # beam mass in amu (only needed for magnetic steering)
beam_chargestate: # beam chargestate (only needed for magnetic steering)
steering_elements:
  MEBT:Q6:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 60.0
    starting_mean: 30.0
    starting_var: 6.0
    max_incremental_change: 60.0
    set_zero_crossing: false
  MEBT:Q7:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 60.0
    starting_mean: 30.0
    starting_var: 6.0
    max_incremental_change: 60.0
    set_zero_crossing: false
  MEBT:YCB7A:CUR:
    type: steerer
    lower_bound: -100.0
    upper_bound: 100.0
    starting_mean: 0.0
    starting_var: 20.0
    max_incremental_change: 200.0
    set_zero_crossing: true
  MEBT:YCB7B:CUR:
    type: steerer
    lower_bound: -100.0
    upper_bound: 100.0
    starting_mean: 0.0
    starting_var: 20.0
    max_incremental_change: 200.0
    set_zero_crossing: true
  MEBT:Q8:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 60.0
    starting_mean: 30.0
    starting_var: 6.0
    max_incremental_change: 60.0
    set_zero_crossing: false
  MEBT:Q9:CUR:
    type: quad
    lower_bound: 0.0
    upper_bound: 60.0
    starting_mean: 30.0
    starting_var: 6.0
    max_incremental_change: 60.0
    set_zero_crossing: false
measurement_device:
  type: fc
  loc: 337.50198000000006
  pv: MEBT:FC9:SCALECUR
  measure_points: 20
  trim_ratio: 0.2
  ptime: 0.01
  scale_factor: 1000000000000
common_elements: {}
#scale factor is a fudge factor to make all FC measurements be in pA
