jaya_url: "https://vpn.devel.hla.triumf.ca/jaya/"
initial_transmission: 1 #write value initial cup reading in pA
beam_energy: 20 #beam energy in keV
beam_mass: 20 # beam mass in amu (only needed for magnetic steering)
beam_chargestate: 4 # beam chargestate (only needed for magnetic steering)
steering_elements:
  IOS:YCB3:VOL:
    type: steerer
    lower_bound: 0.0
    upper_bound: 1000.0
    starting_mean: 500.0
    starting_var: 100.0
    max_incremental_change: 1000.0
    set_zero_crossing: false
    commonis: IOS:CCB1:VOL
  IOS:YCB4:VOL:
    type: steerer
    lower_bound: 0.0
    upper_bound: 1000.0
    starting_mean: 500.0
    starting_var: 100.0
    max_incremental_change: 1000.0
    set_zero_crossing: false
    commonis: IOS:CCB4:VOL
  IOS:YCB6:VOL:
    type: steerer
    lower_bound: 0.0
    upper_bound: 1000.0
    starting_mean: 500.0
    starting_var: 100.0
    max_incremental_change: 1000.0
    set_zero_crossing: false
    commonis: IOS:CCB4:VOL
measurement_device:
  type: fc
  loc: 227.181
  pv: IOS:FC6:SCALECUR
  measure_points: 20
  trim_ratio: 0.2
  ptime: 0.01
  scale_factor: 1000000000000
common_elements:
  IOS:CCB1:VOL:
    type: steerer
    loc: 44.57600000000001
    lower_bound: 0.0
    upper_bound: 1000.0
    starting_mean: 500.0
    starting_var: 100.0
    max_incremental_change: 1000.0
    set_zero_crossing: false
    commonto:
    - IOS:YCB3:VOL
    - IOS:XCB1:VOL
    - IOS:YCB1:VOL
    - IOS:YCB1A:VOL
  IOS:CCB4:VOL:
    type: steerer
    loc: 149.54000000000002
    lower_bound: 0.0
    upper_bound: 1000.0
    starting_mean: 500.0
    starting_var: 100.0
    max_incremental_change: 1000.0
    set_zero_crossing: false
    commonto:
    - IOS:YCB4:VOL
    - IOS:YCB6:VOL
#scale factor is a fudge factor to make all FC measurements be in pA
