"""
For one trained surrogate (seed s, N training runs) and one or more VAE
checkpoints sharing that same (seed, N, val_frac), measure whether the
VAE's decoded ẑ produces landscape predictions that are meaningfully
better than a VAE-free baseline.

The question this script answers
--------------------------------
Is the latent z generated by the VAE's encoder actually informative about
the run's landscape, OR is decode(ẑ) indistinguishable from the training
distribution mean δ̄?  The surrogate ĝ(x, δ) ≈ y is our cheap stand-in for
TRANSOPTR — it lets us compute landscape-fidelity metrics without
re-simulating.  Because the surrogate has systematic bias (R² ≈ 0.35), we
compare *paired differences* across δ choices on the same runs, which
cancels any δ-independent surrogate error.

The four δ choices evaluated per val run
----------------------------------------
  true     δ = δ_true            oracle upper bound — the surrogate's
                                 best possible landscape given the run
  decoded  δ = decode(μ_φ)       what the VAE actually produces
  mean     δ = δ̄_train           training-mean baseline = decode(z=0)
                                 under the VAE's KL regularization;
                                 this is the "no VAE" reference
                                 in Stage 4 of the proposal
  zero     δ = 0 (physical)      perfectly aligned machine, secondary
                                 completeness check

Layered interpretation
----------------------
Layer 0 — surrogate sanity.  Does MSE(true) < MSE(mean) on val runs?
  If no, the surrogate is not responsive to δ at all and the downstream
  comparison is meaningless.  Hard-fail early if so.

Layer 1 — VAE signal.  Does MSE(decoded) < MSE(mean) on val runs?
  Paired Wilcoxon signed-rank across runs.  A statistically significant
  negative difference is evidence the VAE's latent carries real
  landscape-relevant information.

Alignment requirements
----------------------
Surrogate and VAE must share the training seed, val_frac, and (implicitly)
the same MultiFolderRunDataset ordering — otherwise their val splits
differ and the paired comparison is invalid.  This is asserted.

Outputs
-------
  <out_dir>/per_checkpoint_<d_z>.json  per-VAE-checkpoint full results
  <out_dir>/summary.json               aggregate across all checkpoints
"""
from __future__ import annotations

import argparse
import json
import sys
import time
from pathlib import Path
from typing import Optional

import numpy as np
import torch

# Match the import pattern of verify_dz.py
_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from .data import MultiFolderRunDataset, StandardizationStats
from .decoder import MisalignmentDecoder
from .encoder import DeepSetsEncoder
from .model import VAE
from .surrogate import LandscapeSurrogate, load_surrogate


# ═════════════════════════════════════════════════════════════════════
# Split recovery — kept in sync with verify_dz.recover_split
# ═════════════════════════════════════════════════════════════════════

def recover_split(n_items: int, val_frac: float = 0.2, seed: int = 0):
    """Mirror of train.py's train_val_split."""
    rng = np.random.RandomState(seed)
    idx = np.arange(n_items)
    rng.shuffle(idx)
    n_val = max(1, int(round(val_frac * n_items)))
    val_idx = sorted(idx[:n_val].tolist())
    train_idx = sorted(idx[n_val:].tolist())
    return train_idx, val_idx


# ═════════════════════════════════════════════════════════════════════
# VAE loading (same contract as verify_dz.load_vae_checkpoint)
# ═════════════════════════════════════════════════════════════════════

def load_vae_checkpoint(ckpt_path: Path):
    ck = torch.load(ckpt_path, map_location="cpu", weights_only=False)
    cfg = ck["config"]
    stats = StandardizationStats.from_dict(ck["stats"])
    encoder = DeepSetsEncoder(
        d_input=cfg["d_input"] + 1,
        d_hidden=cfg.get("d_hidden", 128),
        d_latent=cfg["d_latent"],
    )
    decoder = MisalignmentDecoder(
        d_latent=cfg["d_latent"],
        d_hidden=cfg.get("d_hidden", 128),
        d_delta=cfg["d_delta"],
    )
    vae = VAE(encoder, decoder, beta=cfg.get("beta", 1.0))
    vae.load_state_dict(ck["model_state"])
    vae.eval()
    return vae, stats, cfg


# ═════════════════════════════════════════════════════════════════════
# Alignment assertion
# ═════════════════════════════════════════════════════════════════════

def assert_aligned(sgt_cfg: dict, vae_cfg: dict, n_ds_runs: int, ckpt_path: Path):
    """
    Hard-stop if the surrogate and VAE checkpoint don't share the exact
    training conditions needed for valid paired comparison.

    Requirements:
      - same seed (determines the shuffle)
      - same val_frac (determines how many runs land in val)
      - same n_runs_total as the current dataset (otherwise the recovered
        val set refers to different runs)
    """
    problems = []
    if "seed" not in vae_cfg:
        problems.append(
            f"VAE checkpoint {ckpt_path} has no 'seed' in config — "
            f"cannot recover val split. Re-train with the updated train.py."
        )
    elif sgt_cfg.get("seed") != vae_cfg.get("seed"):
        problems.append(
            f"seed mismatch: surrogate={sgt_cfg.get('seed')}, "
            f"VAE {ckpt_path}={vae_cfg.get('seed')}"
        )

    if sgt_cfg.get("val_frac", 0.2) != vae_cfg.get("val_frac", 0.2):
        problems.append(
            f"val_frac mismatch: surrogate={sgt_cfg.get('val_frac')}, "
            f"VAE {ckpt_path}={vae_cfg.get('val_frac')}"
        )

    n_sgt = sgt_cfg.get("n_runs_total", n_ds_runs)
    n_vae = vae_cfg.get("n_runs", n_ds_runs)
    if n_sgt != n_ds_runs or n_vae != n_ds_runs:
        problems.append(
            f"dataset size mismatch: surrogate_n={n_sgt}, "
            f"VAE {ckpt_path}_n={n_vae}, current_dataset_n={n_ds_runs}. "
            f"Check that --data_dir is the same as what these were trained on, "
            f"in the same order."
        )

    if problems:
        raise ValueError("Split alignment check failed:\n  " + "\n  ".join(problems))


# ═════════════════════════════════════════════════════════════════════
# Per-run prediction under four δ choices
# ═════════════════════════════════════════════════════════════════════

@torch.no_grad()
def predict_run_landscape(
    surrogate: LandscapeSurrogate,
    sgt_stats: StandardizationStats,
    x_std: np.ndarray,             # (N_j, d_input) standardized with sgt_stats
    delta_std: np.ndarray,         # (d_delta,) standardized with sgt_stats
) -> np.ndarray:
    """
    Run the surrogate on one run's x-grid with a single δ.
    Returns y_hat in STANDARDIZED units, shape (N_j,).
    """
    x_t = torch.from_numpy(x_std.astype(np.float32))
    d_t = torch.from_numpy(delta_std.astype(np.float32))
    return surrogate(x_t, d_t).cpu().numpy()


@torch.no_grad()
def encode_run(vae: VAE, vae_stats: StandardizationStats,
               pairs_std: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Encode one run's (x,y) pairs → (μ_φ, decoded δ̂) in physical units."""
    pairs_t = torch.from_numpy(pairs_std.astype(np.float32)).unsqueeze(0)
    mask_t = torch.ones(1, pairs_t.shape[1], dtype=torch.bool)
    mu, _ = vae.encoder(pairs_t, mask_t)
    delta_hat_std = vae.decoder(mu).squeeze(0).cpu().numpy()
    delta_hat_phys = delta_hat_std * vae_stats.delta_std + vae_stats.delta_mean
    return mu.squeeze(0).cpu().numpy(), delta_hat_phys


def evaluate_one_run(
    ds: MultiFolderRunDataset,
    run_idx: int,
    vae: VAE,
    vae_stats: StandardizationStats,
    surrogate: LandscapeSurrogate,
    sgt_stats: StandardizationStats,
) -> dict:
    """
    For one val run, compute landscape MSE under four δ choices, plus
    secondary peak-transmission diagnostic.

    Returns dict with per-δ-choice standardized and physical MSE, plus
    predicted peak T under each choice.
    """
    rows = ds._run_row_idx[run_idx]
    x_phys = ds.inputs[rows]                       # (N_j, d_input)
    y_phys = ds.transmission[rows]                 # (N_j,)
    delta_true_phys = ds._run_deltas[run_idx]      # (d_delta,)

    # Standardize with VAE stats to get the encoder's view
    # (so the decoded δ̂ physical value uses VAE stats on the way back).
    x_std_vae = (x_phys - vae_stats.input_mean) / vae_stats.input_std
    y_std_vae = (y_phys - vae_stats.y_mean) / vae_stats.y_std
    pairs_std_vae = np.concatenate([x_std_vae, y_std_vae[:, None]], axis=1)

    mu, delta_decoded_phys = encode_run(vae, vae_stats, pairs_std_vae)

    # The surrogate needs EVERYTHING standardized with its own stats.
    # We re-standardize once per choice of δ because the δ itself
    # depends on the choice.
    x_std_sgt = (x_phys - sgt_stats.input_mean) / sgt_stats.input_std
    y_std_sgt = (y_phys - sgt_stats.y_mean) / sgt_stats.y_std

    # δ̄_train is exactly sgt_stats.delta_mean in physical units.
    delta_choices_phys = {
        "true":    delta_true_phys,
        "decoded": delta_decoded_phys,
        "mean":    sgt_stats.delta_mean.copy(),
        "zero":    np.zeros_like(delta_true_phys),
    }

    results = {}
    for name, d_phys in delta_choices_phys.items():
        d_std = (d_phys - sgt_stats.delta_mean) / sgt_stats.delta_std
        y_hat_std = predict_run_landscape(surrogate, sgt_stats, x_std_sgt, d_std)

        # Standardized MSE — what the surrogate was trained on
        resid_std = y_hat_std - y_std_sgt
        mse_std = float(np.mean(resid_std ** 2))

        # Physical MSE — interpretable in transmission units (0-1)
        y_hat_phys = y_hat_std * sgt_stats.y_std + sgt_stats.y_mean
        resid_phys = y_hat_phys - y_phys
        mse_phys = float(np.mean(resid_phys ** 2))

        # Secondary diagnostic: surrogate-predicted peak transmission
        t_peak_hat = float(np.max(y_hat_phys))

        results[name] = {
            "mse_std": mse_std,
            "mse_phys": mse_phys,
            "t_peak_hat": t_peak_hat,
        }

    # Truth-side peak (observed, for context on the t_peak comparisons)
    t_peak_true = float(np.max(y_phys))

    # How far is decoded δ̂ from true and from mean, in standardized space?
    # This is a direct answer to "did the VAE move z away from 0?"
    dec_std = (delta_decoded_phys - vae_stats.delta_mean) / vae_stats.delta_std
    true_std = (delta_true_phys - vae_stats.delta_mean) / vae_stats.delta_std
    dec_vs_true = float(np.mean((dec_std - true_std) ** 2))
    dec_vs_mean = float(np.mean(dec_std ** 2))  # δ̄ is 0 in std space

    return {
        "run_idx": run_idx,
        "run_label": {
            "run_id": ds.run_labels[run_idx].run_id,
            "folder": ds.run_labels[run_idx].folder,
            "axis":   ds.run_labels[run_idx].axis,
            "local_id": ds.run_labels[run_idx].local_id,
        },
        "n_pairs": int(len(rows)),
        "t_peak_true": t_peak_true,
        "mu": mu.tolist(),
        "dec_vs_true_std_mse": dec_vs_true,
        "dec_vs_mean_std_mse": dec_vs_mean,
        "per_delta": results,
    }


# ═════════════════════════════════════════════════════════════════════
# Paired stats & pretty printing
# ═════════════════════════════════════════════════════════════════════

def wilcoxon_signed_rank(diffs: np.ndarray) -> Optional[float]:
    """
    Paired Wilcoxon signed-rank test, two-sided. Returns p-value, or None
    if scipy isn't available or diffs are trivially zero.
    """
    try:
        from scipy.stats import wilcoxon
    except ImportError:
        return None
    diffs = diffs[diffs != 0]  # wilcoxon drops exact zeros by default
    if len(diffs) < 3:
        return None
    try:
        return float(wilcoxon(diffs).pvalue)
    except ValueError:
        return None


def aggregate_paired(per_run: list[dict], key_a: str, key_b: str,
                     metric: str = "mse_std") -> dict:
    """
    For runs where both key_a and key_b produced a result, return paired
    stats of (a - b): mean, median, std, fraction where a < b, and
    Wilcoxon p.
    """
    diffs = []
    for r in per_run:
        a = r["per_delta"].get(key_a)
        b = r["per_delta"].get(key_b)
        if a is None or b is None:
            continue
        diffs.append(a[metric] - b[metric])
    if not diffs:
        return {"n": 0}
    d = np.array(diffs)
    return {
        "n": int(len(d)),
        "mean":   float(d.mean()),
        "median": float(np.median(d)),
        "std":    float(d.std()),
        "frac_a_lt_b": float((d < 0).sum() / len(d)),
        "wilcoxon_p": wilcoxon_signed_rank(d),
    }


def print_summary(d_z: int, agg: dict, layer0_ok: bool):
    """Human-readable one-shot summary per checkpoint."""
    def fmt(name, a, b):
        s = agg[f"{a}_minus_{b}"]
        if not s["n"]:
            return f"  {name:30s}  (no data)"
        p = s["wilcoxon_p"]
        p_str = f"p={p:.4f}" if p is not None else "p=n/a"
        return (f"  {name:30s}  "
                f"mean={s['mean']:+.5f}  med={s['median']:+.5f}  "
                f"frac<0={s['frac_a_lt_b']*100:4.1f}%  {p_str}  (n={s['n']})")

    print(f"\n═══ d_z={d_z} ═══")
    print(fmt("oracle benefit     (true - mean)", "true", "mean"))
    print(fmt("VAE signal         (decoded - mean)", "decoded", "mean"))
    print(fmt("VAE shortfall      (decoded - true)", "decoded", "true"))
    print(fmt("mean vs zero_phys  (mean - zero)",   "mean",    "zero"))

    if not layer0_ok:
        print("  ⚠ Layer 0 FAIL — surrogate not responsive to δ on val runs.")
        print("    Layer 1 interpretation is unreliable; see per_run JSON.")
    else:
        vae_sig = agg["decoded_minus_mean"]
        p = vae_sig.get("wilcoxon_p")
        if vae_sig["mean"] < 0 and p is not None and p < 0.05:
            print(f"  ✓ VAE signal detected: decoded beats mean at p={p:.4f}")
        elif vae_sig["mean"] < 0:
            print(f"  ~ VAE signal weakly negative (mean diff = {vae_sig['mean']:+.5f}), "
                  f"but not significant at p<0.05")
        else:
            print(f"  ✗ No VAE signal: decoded is no better than mean "
                  f"(diff = {vae_sig['mean']:+.5f})")


# ═════════════════════════════════════════════════════════════════════
# Main sweep
# ═════════════════════════════════════════════════════════════════════

def run(
    surrogate_path: Path,
    vae_checkpoints: list[Path],
    data_dirs: list[Path],
    out_dir: Path,
):
    out_dir.mkdir(parents=True, exist_ok=True)

    # ----- load surrogate once -----
    print(f"[load] surrogate: {surrogate_path}")
    surrogate, sgt_stats, sgt_cfg, sgt_epoch, sgt_vm = load_surrogate(surrogate_path)
    print(f"       seed={sgt_cfg.get('seed')}, val_frac={sgt_cfg.get('val_frac')}, "
          f"n_runs_total={sgt_cfg.get('n_runs_total')}, "
          f"best epoch={sgt_epoch}, val_r2={sgt_vm.get('r2', 'n/a')}")

    # ----- dataset -----
    print(f"[load] dataset: {data_dirs}")
    ds = MultiFolderRunDataset(data_dirs, standardize=False)
    print(ds.summary())

    # ----- shared val split recovery -----
    # All VAE checkpoints share the surrogate's split (assert_aligned
    # enforces this), so recover it once.
    val_idx_surrogate = set(recover_split(
        len(ds),
        val_frac=sgt_cfg.get("val_frac", 0.2),
        seed=sgt_cfg["seed"],
    )[1])
    print(f"[split] {len(val_idx_surrogate)} val runs recovered from surrogate config")

    # ----- per-checkpoint loop -----
    summary = {
        "surrogate": str(surrogate_path),
        "surrogate_config": sgt_cfg,
        "surrogate_val_metrics": sgt_vm,
        "data_dirs": [str(d) for d in data_dirs],
        "n_val_runs": len(val_idx_surrogate),
        "checkpoints": [],
    }

    for ckpt_path in vae_checkpoints:
        print(f"\n[ckpt ] {ckpt_path}")
        vae, vae_stats, vae_cfg = load_vae_checkpoint(ckpt_path)
        d_z = vae_cfg["d_latent"]
        print(f"       d_z={d_z}, seed={vae_cfg.get('seed')}, "
              f"val_frac={vae_cfg.get('val_frac')}, n_runs={vae_cfg.get('n_runs')}")

        # HARD STOP on misalignment
        assert_aligned(sgt_cfg, vae_cfg, len(ds), ckpt_path)

        # Evaluate each val run
        per_run = []
        t0 = time.time()
        for i, run_idx in enumerate(sorted(val_idx_surrogate)):
            per_run.append(evaluate_one_run(
                ds, int(run_idx), vae, vae_stats, surrogate, sgt_stats,
            ))
        print(f"[eval ] {len(per_run)} val runs in {time.time()-t0:.1f}s")

        # Paired aggregates for the four key comparisons
        agg = {
            "true_minus_mean":    aggregate_paired(per_run, "true", "mean"),
            "decoded_minus_mean": aggregate_paired(per_run, "decoded", "mean"),
            "decoded_minus_true": aggregate_paired(per_run, "decoded", "true"),
            "mean_minus_zero":    aggregate_paired(per_run, "mean", "zero"),
        }

        # Layer 0 check: does oracle beat mean?
        layer0 = agg["true_minus_mean"]
        layer0_ok = (layer0["n"] > 0
                     and layer0["mean"] < 0
                     and (layer0.get("wilcoxon_p") is None
                          or layer0["wilcoxon_p"] < 0.05))

        # Also record simple marginal (non-paired) per-choice means for context
        marginals = {}
        for key in ("true", "decoded", "mean", "zero"):
            mses = [r["per_delta"][key]["mse_std"] for r in per_run]
            phys = [r["per_delta"][key]["mse_phys"] for r in per_run]
            t_pk = [r["per_delta"][key]["t_peak_hat"] for r in per_run]
            marginals[key] = {
                "mse_std_mean":  float(np.mean(mses)),
                "mse_phys_mean": float(np.mean(phys)),
                "t_peak_hat_mean": float(np.mean(t_pk)),
            }
        marginals["observed_t_peak_true_mean"] = float(np.mean([
            r["t_peak_true"] for r in per_run
        ]))

        # Decoder drift summary: how far is decode(ẑ) from δ̄ and from δ_true?
        decoder_drift = {
            "mean_dec_vs_true_std_mse": float(np.mean(
                [r["dec_vs_true_std_mse"] for r in per_run])),
            "mean_dec_vs_mean_std_mse": float(np.mean(
                [r["dec_vs_mean_std_mse"] for r in per_run])),
        }

        print_summary(d_z, agg, layer0_ok)

        # Per-checkpoint output file
        ckpt_out = {
            "checkpoint": str(ckpt_path),
            "d_latent": d_z,
            "config": vae_cfg,
            "layer0_ok": bool(layer0_ok),
            "aggregate": agg,
            "marginals": marginals,
            "decoder_drift": decoder_drift,
            "per_run": per_run,
        }
        out_file = out_dir / f"per_checkpoint_dz{d_z}.json"
        with open(out_file, "w") as f:
            json.dump(ckpt_out, f, indent=2)
        print(f"[save ] {out_file}")

        summary["checkpoints"].append({
            "path": str(ckpt_path),
            "d_latent": d_z,
            "layer0_ok": bool(layer0_ok),
            "aggregate": agg,
            "marginals": marginals,
            "decoder_drift": decoder_drift,
            "per_run_path": str(out_file),
        })

    with open(out_dir / "summary.json", "w") as f:
        json.dump(summary, f, indent=2)
    print(f"\n[done ] summary at {out_dir / 'summary.json'}")
    return summary


# ═════════════════════════════════════════════════════════════════════
# CLI
# ═════════════════════════════════════════════════════════════════════

def main():
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    p.add_argument("--surrogate", required=True, type=Path,
                   help="Path to surrogate best.pt (e.g. runs/surrogate/sgt_s0/best.pt)")
    p.add_argument("--vae_checkpoint", action="append", required=True, dest="vae_checkpoints",
                   help="Path to a VAE best.pt. Repeatable — one per d_z you want to compare. "
                        "ALL must share (seed, val_frac, n_runs) with the surrogate.")
    p.add_argument("--data_dir", action="append", required=True, dest="data_dirs",
                   help="Same data dirs in the same order as were used for training "
                        "the surrogate AND the VAE checkpoints. Repeatable.")
    p.add_argument("--out_dir", default="runs/compare_latent", type=Path)
    args = p.parse_args()

    run(
        surrogate_path=args.surrogate,
        vae_checkpoints=[Path(c) for c in args.vae_checkpoints],
        data_dirs=[Path(d) for d in args.data_dirs],
        out_dir=args.out_dir,
    )


if __name__ == "__main__":
    main()
